context.properties = {
    default.clock.rate          = 96000
    default.clock.allowed-rates = [ 96000 ]
    default.clock.quantum = 2048
    default.clock.min-quantum = 2048
    default.clock.max-quantum = 2048
    default.resample.quality = 11
}
