context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Virtual Microphone"
            capture.props = {
                node.name        = "virtual_mic_sink"
                node.description = "Virtual Mic Input"
                media.class      = Audio/Sink
                audio.position   = [ FL FR ]
            }
            playback.props = {
                node.name        = "virtual_mic"
                node.description = "Virtual Microphone"
                media.class      = Audio/Source
                audio.position   = [ FL FR ]
            }
        }
    }
]
